### ISSUE TITLE
Color inconsistency in the background

### ISSUE THREAD

**Issue by petrirh1** [akamud/vscode-theme-onedark#113] opened 2019-03-02 16:46 UTC
Just noticed this inconsistency in the background color. 

<a href="https://imgur.com/1tuydlr"><img src="https://i.imgur.com/1tuydlrh.jpg" title="source: imgur.com" /></a>

**Comment by akamud** [comment] 2019-03-03 14:37
Are you on a Mac? This has been reported before and it looks like it is a bug in VSCode itself. See #47 and #33.

**Comment by petrirh1** [comment] 2019-03-03 14:38
Im on Windows, but thanks for letting me know  about this.

**Comment by akamud** [comment] 2019-03-03 14:44
Please let us know if you find anything useful related to this issue. For now I'll be closing this since it looks like a regression bug from VSCode/Chromium.

**Closed by akamud** 2019-03-03 14:44 UTC
