### ISSUE TITLE
Rust analyzer extension’s assumed type declarations have an incorrect background colour

### ISSUE THREAD

**Issue by NashJames** [akamud/vscode-theme-onedark#154] opened 2022-10-05 11:53 UTC
Hey, I’ve come back to rust after some time away and it seems something with the Rust Analyzer extension changed so I get these awful blue boxes with one dark now. Obviously, they should just be the same colour as the background.

Not sure if it’s the extensions fault or this theme, but I was wondering if there’s any customisation line I can add to the preferences.json to fix it manually?

Thanks for the help.

![2D1C84A1-D17E-4CB6-BE8F-C68F699A20B1](https://user-images.githubusercontent.com/37304960/194051477-923b2283-bd80-4952-99b6-5abfcc8e50e2.jpeg)

**Comment by akamud** [comment] 2022-10-08 12:31
Hi, I think this is a duplicate of #146, you can see a workaround on that issue. Please feel free to reopen this if you believe it is not a duplicate.

**Closed by akamud** 2022-10-08 12:31 UTC
Labels: color-inconsistency
