### ISSUE TITLE
White space color in the new selection option is not readable

### ISSUE THREAD

**Issue by marcjoselnario** [akamud/vscode-theme-onedark#116] opened 2019-08-12 06:39 UTC
![image](https://user-images.githubusercontent.com/18049741/62848587-ec1c9a00-bd0e-11e9-811e-263b568f1475.png)

## Versions used

* VSCode version: 1.37.0
* Theme version: 2.1.0

**Comment by akamud** [comment] 2020-03-15 19:59
Duplicate of #121, fixed in 2.2.0.

**Closed by akamud** 2020-03-15 19:59 UTC
Labels: color-inconsistency
