### ISSUE TITLE
JavaScript Grammer

### ISSUE THREAD

**Issue by a-heryani** [akamud/vscode-theme-onedark#125] opened 2020-05-03 21:02 UTC
Please see the screenshot below. The variable "hasPromotion" is coloured differently when it is declared vs when it is used in the function.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/26278881/80925667-177f7180-8dd5-11ea-8171-c8d1027adbe1.png">

**Comment by akamud** [comment] 2020-05-05 12:44
Duplicate of #84

**Closed by akamud** 2020-05-05 12:44 UTC
Labels: duplicate
